// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo1.Models;

[Index("account", Name = "IX_Customer", IsUnique = true)]
public partial class Customer
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string account { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string password { get; set; }

    [StringLength(30)]
    public string name { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string tel { get; set; }

    [StringLength(50)]
    public string address { get; set; }

    public bool? employee { get; set; }

    [InverseProperty("cust")]
    public virtual ICollection<Orderdetail> Orderdetail { get; set; } = new List<Orderdetail>();
}