// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo1.Models;

public partial class Orderdetail
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ordersnum { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string account { get; set; }

    public DateOnly? orderdate { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string productnum { get; set; }

    [StringLength(50)]
    public string producttitle { get; set; }

    public int? qty { get; set; }

    public int? price { get; set; }

    public int? total { get; set; }
}