// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Demo1.Models;

public partial class Product
{
    [Key]
    [StringLength(5)]
    [Unicode(false)]
    public string num { get; set; }

    [StringLength(50)]
    public string title { get; set; }

    public int? price { get; set; }

    [StringLength(30)]
    public string img { get; set; }

    [StringLength(5)]
    public string kind { get; set; }

    [InverseProperty("productnumNavigation")]
    public virtual ICollection<Orderdetail> Orderdetail { get; set; } = new List<Orderdetail>();
}